config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :vgas

  resources :cpus

  resources :calcs

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :cpus
end

app/models/calc.rb
class Calc < ApplicationRecord
  belongs_to :cpu
  belongs_to :vga,optional:true
  belongs_to :ram
  belongs_to :water_cooling
  belongs_to :motherboard


  validates :cpu,:ram,:water_cooling,:motherboard,:fan_count,:ram_count,:sata_count, presence:true
  def calculation(calc,vga_present)
    calc.calc = ((calc.cpu.power + vga_power(vga_present) + ram_power + fan_power + calc.water_cooling.water_power + calc.motherboard.power + sata_power) * 1.3).to_i
  end
  def vga_power(vga_present)
    if vga_present
      self.vga.vga_power * (vga_count > 0 ? vga_count : 1)
    else
       0
    end
  end
  def ram_power
    self.ram.power_ram * self.ram_count
  end
  def fan_power
    self.fan_count * 3
  end
  def sata_power
    self.sata_count * 25
  end

  end

app/models/company.rb
class Company < ApplicationRecord
  has_many :cpus
  has_many :vgas
end

app/models/cpu.rb
class Cpu < ApplicationRecord
  belongs_to :company
  belongs_to :brand
  belongs_to :socket_cpu
end

app/models/motherboard.rb
class Motherboard < ApplicationRecord
end

app/models/ram.rb
class Ram < ApplicationRecord
  belongs_to :brand
end

app/models/socket_cpu.rb
class SocketCpu < ApplicationRecord
  has_many :cpus
end

app/models/vga.rb
class Vga < ApplicationRecord
  belongs_to :company
  belongs_to :brand,optional:true
end

app/models/water_cooling.rb
class WaterCooling < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/calcs_controller.rb
class CalcsController < ApplicationController
  def index
  end

  def new
   @calc = Calc.new
  end

  def create
    @calc = Calc.create(calc_params)
    if @calc.valid?
      @calc.save
      @calc.calculation(@calc, calc_params[:vga_id].present?)
    else
      render 'calcs/new'
    end
  end

  private
  def calc_params
    params.require(:calc).permit(:cpu_id,:vga_id,:ram_count,:ram_id,
                                 :vga_count,:fan_count,:water_cooling_id,
                                 :motherboard_id,:sata_count)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calcs_helper.rb
module CalcsHelper
end

app/helpers/cpus_helper.rb
module CpusHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vgas_helper.rb
module VgasHelper
end

app/views/calcs/create.html.haml
.div
  .row
    .col-md-8
      .alert.alert-success
        %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "/calcs/new"} ×
        %h2
          The recommended minimum power supply:
        %h1.text-center
          =@calc.calc.to_s+' W!'
        %h4
          Said capacity - a maximum rate of consumption of all components. The total number of measured counting on all devices operating at peak consumption.
          It is important to bear in mind that this amount will never be achieved through normal operation.
        = link_to 'Success', new_calc_path,class:'btn btn-lg btn-primary center'

app/views/calcs/new.html.haml
- if @calc.errors.any?
  .alert.alert-danger.alert-dismissable
    %a.close{"aria-label" => "close", "data-dismiss" => "alert", :href => "#"} ×
    %strong Please fix this errors
    #{ pluralize(@calc.errors.count, "error")}
    %ul
      - @calc.errors.full_messages.each do |msg|
        %li
          = msg
.div
  .row
    .col-md-6
      = form_for @calc, method: :post do |f|
        =f.label 'Cpu'
        %br
        =f.select :cpu_id, Cpu.all.collect {|p| [ (Company.find(p.company).name+' '+Brand.find(p.brand_id).name+' '+p.name+' Socket '+SocketCpu.find(p.socket_cpu_id).name).to_s, p.id ] }, { include_blank: true },id:'ec1'
        %br
        =f.label 'Vga'
        %br
        =f.select :vga_id, Vga.all.collect {|p| [ (Company.find(p.company_id).name+' '+Brand.find(p.brand_id).name+' '+p.name).to_s, p.id ] }, { include_blank: true },id:'ec2'
        =f.select :vga_count, (1..4).to_a {|p| [ 'x', p ] }, { include_blank: true },id:'ec3',style:'width: 60px;'
        %br
        =f.label 'Ram'
        %br
        =f.select :ram_id, Ram.all.collect {|p| [ Brand.find(p.brand_id).name.to_s+'   ', p.id ] }, { include_blank: true },id:'ec4',style:'width: 90px;'
        =f.select :ram_count, (0..8).to_a {|p| [ 'x', p ] }, { include_blank: true },id:'ec5',style:'width: 60px;'
        %br
        =f.label 'Fan count'
        %br
        =f.select :fan_count, (0..10).to_a {|p| [ 'x', p ] }, { include_blank: true },id:'ec6',style:'width: 60px;'
        %br
        =f.label 'Water cooling'
        %br
        =f.select :water_cooling_id, WaterCooling.all.collect {|p| [ 'Pomp '+p.pomp_count.to_s+'x'+', Fan'+p.fan_count.to_s+'x', p.id ] }, { include_blank: true },id:'ec7',style:'width: 150px;'
        %br
        =f.label 'Motherboard'
        %br
        =f.select :motherboard_id, Motherboard.all.collect {|p| [ p.name, p.id ] }, { include_blank: true },id:'ec8'
        %br
        =f.label 'Sata & Pata count'
        %br
        =f.select :sata_count, (0..40).to_a {|p| [ 'x', p ] }, { include_blank: true },id:'ec9',style:'width: 60px;'
        %br
        =f.label 'Calculate'
        %br
        =f.submit 'Calculate',url:calcs_path,class:'btn btn-primary btn-lg'
    .col-md-6
      %h1.text.text-success
        Calculation of the power supply unit
        Choose a correct power supply!
      %h3.text
        To avoid possible problems with instability, reboot and power off unexpectedly,
        we suggest you use the following calculator to determine unit with a power supply that best suits your needs.
        The result is a recommended value, summarized for all components that
        you choose - you just buy necessity power supply more power.
:javascript
  $(document).ready(function() {
  $("#ec1").select2();
  $("#ec2").select2();
  $("#ec3").select2();
  $("#ec4").select2();
  $("#ec5").select2();
  $("#ec6").select2();
  $("#ec7").select2();
  $("#ec8").select2();
  $("#ec9").select2();})

app/views/home/index.html.haml
.div
  .row
    .col-md-8
      %h1
        Power
      %h3
        Depending on the accessories, computers may consume power from a few watts to several kilowatts.
        The power supply must be designed so that to cope with the maximum load, and it is desirable to have
        reserves - only in this case it will work effectively and quietly.
        The optimum power BP can be calculated as the sum of the TDP (Thermo) CPU and GPU,
        multiplied by 1.5. So, for the Core i5-4690 processor (TDP 84 Watt) and a graphics card Radeon R9 280X
        (TDP of 250 watts) best fit the power supply capacity of 500 watts. 450-watt unit was loaded to approximately
        80%, to 750 watt - 50%
      = link_to 'To Calculator', new_calc_path,class:'btn btn-lg btn-primary',size:'100'

app/views/layouts/active_admin_logged_out.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8">

  <title><%= [@page_title, render_or_call_method_or_proc_on(self, ActiveAdmin.application.site_title)].compact.join(" | ") %></title>

  <% ActiveAdmin.application.stylesheets.each do |style, options| %>
    <%= stylesheet_link_tag style, options %>
  <% end %>
  <% ActiveAdmin.application.javascripts.each do |path| %>
    <%= javascript_include_tag path %>
  <% end %>

  <%= favicon_link_tag ActiveAdmin.application.favicon if ActiveAdmin.application.favicon %>

  <% ActiveAdmin.application.meta_tags_for_logged_out_pages.each do |name, content| %>
    <%= tag(:meta, name: name, content: content) %>
  <% end %>

  <%= csrf_meta_tag %>
</head>
<body class="active_admin logged_out <%= controller.action_name %>">

<div id="wrapper">

  <div id="content_wrapper">
    <% flash_messages.each do |type, message| %>
      <%= content_tag :div, message, class: "flash flash_#{type}" %>
    <% end %>
    <div id="active_admin_content">
      <%= yield %>
    </div>
  </div>
  <div id="footer">
    <%= yield :footer %>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "PowerSupply"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-inverse.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#{root_path}") PowerSupply
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Calculate", new_calc_path,class:'text text-right'
            %li= link_to "Admin?", "/admin/login",class:'text text-right'
    .container
      = bootstrap_flash
      = yield